apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    {{- include "productpage.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "productpage.selectorLabels" . | nindent 4 }}
