apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    {{- include "details.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "details.selectorLabels" . | nindent 4 }}
