{{- if .Values.global.meshEnabled -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: {{ .Values.mesh.trafficPolicy }}
  subsets:
  - name: {{ include "reviews.version" . }}
    labels:
      version: {{ include "reviews.version" . }}
{{- end -}}